import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const base=path.dirname(fileURLToPath(import.meta.url));
const ui=path.resolve(base,'../../GENERATE/ui-design/stitch-v2');
const read=async p=>JSON.parse((await readFile(p,'utf8')).replace(/^\uFEFF/,''));
const source=await read(path.join(base,'sprint-source.json'));
const previous=await read(path.join(base,'backlog.json'));
const screens=await read(path.join(ui,'task-screen-map.json'));
const project=await read(path.join(ui,'stitch-task-project.json'));
const stitch='https://stitch.withgoogle.com/'+project.name;
await mkdir(path.join(base,'deferred'),{recursive:true});
const deferred=previous.filter(t=>!source.some(s=>s.id===t.id));
if(deferred.length)await writeFile(path.join(base,'deferred/backlog.json'),JSON.stringify(deferred,null,2));
const items=source.map(s=>{
 const old=previous.find(t=>t.id===s.id);
 if(!old)throw Error('Unknown source task '+s.id);
 const main=s.title.split(':')[0];
 const refs=[...s.screenRefs.matchAll(/\b(?:AUTH|SYS|H|T|V|O|M)\d{2}\b/g)].map(m=>m[0]);
 const owned=screens.filter(c=>c.taskId===s.id).map(c=>c.id);
 const mapped=['UI-V2','MVP-QA'].includes(s.id)?screens.map(c=>c.id):[...new Set([...refs,...owned])];
 const ac=s.ac.split(';').map(x=>x.trim()).filter(Boolean);
 return {...old,title:main,taskDetail:s.title,lookup:s.lookup,githubTitle:`[${s.lookup}][${s.id}] ${main}`,sprint:s.sprint,start:s.start,targetDate:s.end,lead:s.lead,assigneePlaceholder:s.assigneePlaceholder,owner:'',screens:mapped,ac,issueUrl:s.url,status:'Todo',branch:s.branch};
});
const byId=new Map(items.map(t=>[t.id,t]));
for(const t of items){
 const dependencies=t.deps.map(d=>{if(!byId.has(d))throw Error('Out-of-scope dependency '+d);return `- [${d}](${byId.get(d).issueUrl})`;}).join('\n')||'- Không có dependency công việc; cần review và phân công.';
 const body=`# ${t.githubTitle}\n\nWork ID: ${t.id}\nMã tra cứu: ${t.lookup}\nBlueprint ID: ${t.fr}\nSprint: ${t.sprint}\nThời gian kế hoạch: ${t.start} – ${t.targetDate}\nLead theo workbook: ${t.lead}\nVị trí phân công theo workbook: ${t.assigneePlaceholder} (chưa phải username GitHub)\nBranch: \`${t.branch}\`\n\n## Nội dung task gốc\n\n${t.taskDetail}\n\nNguồn: [kế hoạch 3 sprint](../EquiFlow_Sprint_Plan_3_Weeks.xlsx). Chỉ website desktop Flow 1–3; không mobile, phả hệ, video hoặc flow optional.\n\n## Giao diện\n\n[Stitch chuẩn theo task](${stitch}) · [Danh mục tên thống nhất](../../GENERATE/ui-design/stitch-v2/SCREEN-MAP-CORE.md)\n\nScreen IDs: ${t.screens.join(', ')||'Không có màn riêng — nền tảng hệ thống'}. Bộ có 31 màn chính và 5 biến thể thao tác/quyền của cùng task; không thêm flow. Tên Canvas dùng cùng mã tra cứu, Work ID và tên task ở trên.\n\n## Acceptance criteria theo task\n\n${t.ac.map(a=>'- [ ] '+a).join('\n')}\n\n## Checklist thực hiện\n\n- [ ] Chốt API/DTO, validation, quyền, trạng thái lỗi và các quyết định còn mở.\n- [ ] FE: layout, routing, form, state và tích hợp API theo screen ID; desktop 1280/1440/1920px.\n- [ ] BE: API/service, migration, quyền và audit phù hợp task; không chỉ vô hiệu hóa nút UI.\n- [ ] QA: kiểm tra dương/âm, RBAC, owner isolation và concurrency phù hợp AC.\n- [ ] PR liên kết issue chính; review, merge, build/test thật và tài liệu/rollback trước Done.\n\n## Dependency\n\n${dependencies}\n\n## Giới hạn và quyết định\n\nStack trong FOUNDATION vẫn là lựa chọn cần chốt, không tự chọn framework. OTP 15 phút, lời mời 48 giờ và cửa sổ cảnh báo y tế 7 ngày theo workbook hiện tại; thay thế đề xuất UI cũ. Mọi lệnh mở Medical Lock chỉ do Vet; không tự mở theo ngày dự kiến. Màn mockup không chứng minh API hoặc kiểm thử nghiệp vụ đã hoàn thành.\n\nStatus triển khai: Todo. Chưa có implementation/test evidence; không gán username giả.\n`;
 await writeFile(path.join(base,'issues',t.id+'.md'),body);
}
await writeFile(path.join(base,'backlog.json'),JSON.stringify(items,null,2));
const keys=['lookup','id','title','sprint','start','targetDate','priority','lead','owner','status','screens','issueUrl'];
const cell=v=>'"'+String(Array.isArray(v)?v.join(';'):v??'').replaceAll('"','""')+'"';
await writeFile(path.join(base,'backlog.csv'),'\uFEFF'+keys.join(',')+'\r\n'+items.map(t=>keys.map(k=>cell(t[k])).join(',')).join('\r\n'));
await writeFile(path.join(base,'todo.md'),'# 20 task core — theo kế hoạch 3 sprint\n\nChỉ website desktop Flow 1–3. Các mục optional ở `deferred/`, không nằm trong kế hoạch triển khai hiện tại.\n\n'+items.map(t=>`- [ ] [${t.githubTitle}](${t.issueUrl}) · ${t.sprint} · ${t.start}–${t.targetDate}`).join('\n')+'\n');
let plan='# Kế hoạch website EquiFlow — Flow 1, 2, 3\n\nNguồn chuẩn: [EquiFlow_Sprint_Plan_3_Weeks.xlsx](EquiFlow_Sprint_Plan_3_Weeks.xlsx), 20 task. Tên/mã task bên dưới được lấy từ workbook; chi tiết kỹ thuật giữ trong từng issue. Chỉ website desktop, không mobile. Không flow optional, cây phả hệ hoặc video.\n\n[Project nhóm](https://github.com/users/MichaelTran1226/projects/2) · [Stitch theo task]('+stitch+') · [Danh mục màn hình](ui/SCREEN-MAP.md) · [Quy chuẩn thiết kế](ui/DESIGN.md)\n\n## Lịch ba sprint\n\n| Sprint | Thời gian | Task | Đầu ra |\n|---|---|---|---|\n| Sprint 1 | 28/09–04/10/2026 | 9 | Nền tảng, UI, auth/RBAC, audit, hồ sơ ngựa |\n| Sprint 2 | 05/10–11/10/2026 | 6 | Ô chuồng và Flow 3 y tế/ảnh 2D/Medical Lock |\n| Sprint 3 | 12/10–18/10/2026 | 5 | Flow 2 huấn luyện và nghiệm thu xuyên suốt |\n\nLịch này là kế hoạch trong workbook, không phải bằng chứng đã hoàn tất hay đảm bảo tiến độ. Các vị trí Frontend Dev/Backend Dev/Fullstack Dev/QA chưa được suy thành username GitHub.\n\n## 20 đầu việc\n\n| Mã tra cứu | Work ID | Tên task thống nhất | Sprint | Phụ thuộc |\n|---|---|---|---|---|\n';
plan+=items.map(t=>`| ${t.lookup} | ${t.id} | [${t.title}](${t.issueUrl}) | ${t.sprint} | ${t.deps.join(', ')||'—'} |`).join('\n');
plan+='\n\n## Thực hiện từng phần\n\n1. Nhận FOUNDATION và UI-V2 trước; chốt stack/DB/runtime/contract. FE và BE làm song song theo contract đã thống nhất.\n2. Hoàn tất auth/session, audit và owner isolation trước API hồ sơ/chuồng.\n3. Triển khai y tế và Medical Lock trước enforcement của huấn luyện. Chỉ Vet khóa/mở; Manager không duyệt thay.\n4. Tạo branch theo workbook; PR liên kết URL issue đầy đủ khi đi qua FE/BE. Không đóng primary issue trước khi các PR liên quan hoàn tất.\n5. QA kiểm tra luồng đăng ký → hồ sơ → chấn thương 2D → khóa → lịch bị chặn → tái khám/mở → xếp lịch mới. Không mở optional trong đợt này.\n\n## Thiết kế bàn giao\n\n31 màn chính theo workbook + 5 biến thể của task hiện có: T03-CREATE (tạo lịch), V02-RX (thêm thuốc), V06-CREATE (lập lịch dự phòng), H04-GROOM (đọc phân công), H03-OWNER (đọc hồ sơ sở hữu). Không tạo task hay flow mới. T04 bổ sung ô nhập chỉ số thay cho telemetry ngoài phạm vi. Mỗi tên Canvas được ghi nguyên văn trong SCREEN-MAP.md và task-screen-map.json.\n\n## Quyết định và nghiệm thu\n\n- Theo task: OTP 6 số/15 phút; lời mời 48 giờ; lịch dự phòng hiển thị cửa sổ sắp đến hạn 7 ngày. SRS trước đó nhắc trước 3 ngày: giữ mốc nhắc gửi 3 ngày nếu chưa có quyết định thay đổi, tách khỏi bộ lọc 7 ngày của UI.\n- Stack, cơ chế cấp Manager đầu tiên, provider email và thời hạn refresh token cần chốt trong FOUNDATION; workbook đưa lựa chọn, chưa chốt framework.\n- Ảnh giải phẫu đúng nguồn 900×600; marker theo tọa độ chuẩn hóa; một góc hệ xương, không 3D.\n- Ready: AC rõ, contract và dependency được giải quyết, có assignee thật. Todo không đồng nghĩa Ready.\n- Done: AC đạt, API/RBAC/concurrency và UI desktop kiểm tra thật; PR review/merge; build/test và rollback có evidence. Thiết kế Stitch không phải ứng dụng đã triển khai.\n';
await writeFile(path.join(base,'plan.md'),plan);
await writeFile(path.join(ui,'SCREEN-MAP-CORE.md'),'# Màn hình website thống nhất theo task\n\n[Stitch]('+stitch+') · 31 màn chính + 5 biến thể cùng task · Không mobile/optional.\n\n| Screen ID | Work ID | Tên chính xác trên Stitch | Nguồn HTML |\n|---|---|---|---|\n'+screens.map(s=>`| ${s.id} | [${s.taskId}](${s.issueUrl}) | ${s.stitchTitle} | [HTML](screens/${s.id}.html) |`).join('\n')+'\n');
await writeFile(path.join(ui,'SCREEN-MAP.md'),await readFile(path.join(ui,'SCREEN-MAP-CORE.md')));
console.log(JSON.stringify({tasks:items.length,screens:screens.length,optionalActive:items.filter(t=>['M3','M4'].includes(t.milestone)).length}));
