import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import path from 'node:path';
const base=path.dirname(fileURLToPath(import.meta.url));
const screenBase=path.resolve(base,'../../GENERATE/ui-design/stitch-v2');
const screens=JSON.parse(await readFile(path.join(screenBase,'screens.json'),'utf8'));
// Work IDs remain stable before GitHub assigns issue numbers.
const tasks=[
['FOUNDATION','FR-022','Chốt stack, contract và nền dự án','M0','P0 Critical','governance',[], 'Điều phối + FE + BE','High',['Ghi quyết định stack/DB/runtime và auth policy, không lấy demo làm quyết định ngầm.','FE và BE khởi động được theo README; migration và health check có evidence.','CI chạy lint/typecheck/test/build thích hợp; .env và credential không được tracked.']],
['UI-V2','FR-022','Duyệt bộ giao diện Stitch V2','M0','P0 Critical','ui',[],'FE + Điều phối','Medium',['Screen map truy nguyên Flow 1–3 + auth/audit; optional tạm hoãn, màn hình riêng và link Stitch thực.','Không phả hệ/video; V03 dùng đúng file ảnh; AUTH01/02/03 tách rõ.','Review website desktop 1280/1440/1920px và state checklist; mọi lệch thiết kế có issue.']],
['AUTH-LOGIN','FR-001','Đăng nhập và session','M0','P0 Critical','auth',['FOUNDATION','UI-V2'],'BE + FE','High',['Credentials hợp lệ tạo session và đưa đúng dashboard của role server cấp.','Sai mật khẩu, account khóa/chưa xác minh và session hết hạn không truy cập dữ liệu.','Logout/thu hồi session được kiểm chứng; password/token không vào URL hoặc log.']],
['AUTH-REGISTER','FR-001','Đăng ký chủ ngựa và xác minh email','M0','P0 Critical','auth',['AUTH-LOGIN'],'BE + FE','High',['Signup không nhận role đặc quyền hoặc ownerId tùy ý; password được xử lý an toàn.','Mã xác minh đúng một lần, hết hạn/giới hạn gửi/lần thử có kiểm chứng; email provider đã chốt.','Xác minh xong vào tài khoản chưa có ngựa; không tự gán ownership; gửi lỗi không giả thành công.']],
['AUTH-RESET','FR-001','Khôi phục mật khẩu','M0','P0 Critical','auth',['AUTH-LOGIN'],'BE + FE','High',['Forgot trả thông báo chung cho email tồn tại/không tồn tại.','Reset token hết hạn/đã dùng bị từ chối; mật khẩu xác nhận sai không được lưu.','Đổi mật khẩu thành công, session xử lý theo policy và login bằng mật khẩu mới đạt E2E.']],
['AUTH-STAFF','FR-001','Mời nhân sự và quản lý quyền','M0','P0 Critical','auth',['AUTH-LOGIN','FR-021'],'BE + FE','Critical',['Lời mời gắn email và role server cấp; hết hạn/thu hồi/đã dùng bị từ chối.','Chỉ người có quyền được mời/đổi role/khóa account; không mất quản trị viên cuối cùng.','Đổi quyền có audit, ảnh hưởng session theo policy; không chỉ ẩn menu.']],
['AUTH-SCOPE','FR-001','RBAC và dữ liệu theo chủ sở hữu','M0','P0 Critical','auth',['AUTH-LOGIN'],'BE + FE + QA','Critical',['Kiểm chứng đủ năm role trên API, trang và hành động sửa; sai quyền bị 403.','Hai Owner không đọc được ngựa/lịch/bệnh án/báo cáo của nhau bằng thay ID.','Scope ownership được tái sử dụng cho export/AI; có test hồi quy khi các module đó xuất hiện.']],
['FR-021','FR-021','Nhật ký kiểm toán','M0','P0 Critical','governance',['AUTH-LOGIN'],'BE + FE','High',['Thao tác nhạy cảm ghi tác nhân, thời gian, đối tượng, kết quả cùng thay đổi nghiệp vụ.','Không có API/UI sửa/xóa audit cho người dùng thường; không lưu credential.','Quản lý lọc/xem log; sai quyền từ chối; test failure/rollback không tạo lịch sử thành công sai.']],
['FR-002','FR-002','Hồ sơ định danh ngựa','M1','P0 Critical','horse',['AUTH-SCOPE','FR-021'],'BE + FE','High',['Tạo/sửa/tìm theo chip; chip duy nhất kể cả hai request đồng thời.','Không xóa vật lý hồ sơ đã có lịch sử; sức khỏe và vòng đời rõ ràng.','Owner chỉ thấy ngựa liên kết đúng; hồ sơ không chứa phả hệ hay video.']],
['FR-003','FR-003','Phân bổ ô chuồng','M1','P0 Critical','horse',['FR-002'],'BE + FE','High',['Chuyển ngựa vào ô trống và gán Groom hợp lệ lưu được, giao diện cập nhật.','Hai người phân cùng ô đồng thời chỉ một thành công; không để ngựa chiếm nhiều ô ngoài quy tắc.','Groom xem đúng phạm vi phân công; xung đột được giải thích và không mất dữ liệu.']],
['FR-008','FR-008','Bảng sức khỏe đàn ngựa','M2','P0 Critical','medical',['FR-002'],'BE + FE','Medium',['Bốn trạng thái sức khỏe có màu và chữ, lọc/tìm đúng dữ liệu.','Medical Lock là thuộc tính hạn chế riêng, không suy tự động từ màu trạng thái.','Trạng thái trống/loading/lỗi và phân quyền đọc đạt kiểm tra viewport.']],
['FR-009','FR-009','Bệnh án và phác đồ','M2','P0 Critical','medical',['FR-008','FR-021'],'BE + FE','High',['Vet lưu bệnh án, phác đồ/thuốc với đơn vị và lịch; người không có quyền không chỉnh được.','Validation không lưu chẩn đoán/thuốc thiếu thông tin bắt buộc; lỗi giữ form.','Lịch sử sửa có audit; chính sách trừ kho được chốt trước tích hợp vật tư.']],
['FR-010','FR-010','Đánh dấu chấn thương trên ảnh 2D','M2','P0 Critical','medical',['FR-009','UI-V2'],'FE + BE','High',['Ảnh đúng SHA256 của asset người dùng; không thay bằng mô hình tự vẽ hay 3D.','Marker lưu và tải lại đúng vị trí ảnh ở 1280/1440/1920px; vùng và bên cơ thể chọn riêng.','Vet sửa, người xem chỉ đọc; keyboard chọn vùng; lỗi tải ảnh/lưu có trạng thái rõ.']],
['FR-011','FR-011','Ban hành và mở khóa y tế','M2','P0 Critical','medical',['FR-009','FR-021'],'BE + FE','Critical',['Chỉ Vet ban hành/gỡ khóa với lý do và đánh giá; ngày dự kiến không tự mở khóa.','Lệnh khóa cập nhật hạn chế và xử lý buổi tập chịu ảnh hưởng nhất quán, có audit.','Mở khóa không tự chạy lại lịch đã đình chỉ; test quyền, retry và concurrency.']],
['FR-004','FR-004','Giáo án theo giai đoạn','M2','P0 Critical','training',['FR-002','FR-011'],'BE + FE','High',['Lưu giai đoạn, cự ly, tốc độ, khối lượng, mặt sân với đơn vị rõ.','Thiếu/âm/sai thời gian bị từ chối; giữ form khi API lỗi.','Không áp dụng giáo án khi bị Medical Lock; không thêm ngoại lệ rehab chưa duyệt.']],
['FR-005','FR-005','Enforcement Medical Lock','M2','P0 Critical','medical',['FR-011','FR-004'],'BE + FE + QA','Critical',['API chặn lập lịch/áp giáo án khi khóa (đăng ký giải để giai đoạn tùy chọn); không phụ thuộc disabled button.','Test hai giao dịch Vet khóa và HLV lưu cùng lúc không tạo lịch vi phạm.','UI nhận từ chối hiển thị lý do và link hồ sơ; không báo thành công, không cho HLV bỏ qua.']],
['FR-006','FR-006','Lịch tập và phân công','M2','P0 Critical','training',['FR-004','FR-005','FR-003'],'BE + FE','High',['Phân công ngựa, Groom/nài, thời gian và bài tập xuất hiện đúng lịch/ca.','Xung đột giờ/nhân sự/ngựa bị từ chối theo contract; Medical Lock kiểm tra lại khi lưu.','Website có lịch tuần và agenda; đổi/hủy lịch có evidence và không tạo role Jockey thứ sáu.']],
['FR-007','FR-007','Kết quả và nhật ký huấn luyện','M2','P0 Critical','training',['FR-006'],'BE + FE','Medium',['HLV ghi kết quả và nhận xét có đơn vị; dữ liệu không hợp lệ bị chặn.','Biểu đồ dùng bản ghi đã lưu, không có dữ liệu không bịa xu hướng.','Owner xem đúng ngựa, không sửa; nhật ký thay video trên portal.']],
['FR-012','FR-012','Lịch y tế dự phòng','M2','P1 High','medical',['FR-009'],'BE + FE','Medium',['Lưu lịch tiêm/tẩy giun/móng, nhắc trước ba ngày theo quy tắc đã thống nhất.','Múi giờ Asia/Ho_Chi_Minh, quá hạn/hoàn tất đúng; gửi lại job không lặp thông báo.','Groom đọc việc được giao, Vet cập nhật; test boundary ngày.']],
['MVP-QA','FR-001,FR-002,FR-003,FR-005,FR-010,FR-011','Nghiệm thu MVP xuyên suốt','M2','P0 Critical','governance',['FR-003','FR-005','FR-007','FR-010','FR-012'],'QA + FE + BE','Critical',['E2E signup→verify→login→horse→injury→lock→blocked scheduling→unlock→reschedule đạt.','Năm role và hai Owner kiểm tra API/UI; asset và marker đúng ở ba viewport.','CI/build/test thực được đính kèm PR; review/merge và rollback có evidence trước Done.']],
['FR-013','FR-013','Khẩu phần theo bữa','M3','P1 High','care',['MVP-QA'],'BE + FE','Medium',['HLV/Vet lập và duyệt lượng/đơn vị từng bữa; Groom không sửa.','Ca chăm sóc chỉ dùng phiên bản đã duyệt; thay đổi có version.','Không lượng âm, thiếu dữ liệu có empty state; quyền và audit được kiểm tra.']],
['FR-014','FR-014','Checklist ca chăm sóc','M3','P1 High','care',['FR-013','FR-003'],'BE + FE','High',['Groom chỉ thao tác ca/ngựa được giao, lưu checklist và giờ hoàn tất.','Ghi chú bất thường text gửi cảnh báo đúng người; không ảnh sự cố/video.','Gửi lặp hoặc mất mạng không nhân đôi hoàn tất/trừ kho; không giả lưu thành công.']],
['FR-015','FR-015','Tồn kho và đề xuất bổ sung','M3','P1 High','care',['FR-014'],'BE + FE','High',['Tồn, đơn vị, ngưỡng cảnh báo và đề xuất được lưu/đọc đúng quyền.','Một sự kiện tiêu hao chỉ trừ một lần; test concurrency không để tồn âm.','Duyệt/từ chối có người, thời gian, lý do; lỗi không âm thầm mất đề xuất.']],
['FR-016','FR-016','Giải đua và đăng ký','M3','P1 High','racing',['MVP-QA','FR-005'],'BE + FE','Critical',['Giải có điều kiện và hạn thật; ngựa không đủ điều kiện có lý do từng dòng.','API chặn trùng/hết hạn/khóa y tế, kể cả khóa đồng thời với đăng ký.','Đăng ký hợp lệ lưu và trả kết quả thật; scope vai trò được kiểm tra.']],
['FR-017','FR-017','Ghi nhận thành tích thi đấu','M3','P1 High','racing',['FR-016'],'BE + FE','Medium',['Kết quả hợp lệ cập nhật hồ sơ ngựa, có nguồn và người nhập.','Thời gian/thứ hạng/tiền thưởng không hợp lệ bị chặn; sửa có lịch sử.','Owner xem đúng kết quả ngựa sở hữu; không tạo thành tích mẫu như dữ liệu thật.']],
['FR-018','FR-018','Báo cáo chi phí và tiền thưởng','M3','P1 High','finance',['FR-017'],'BE + FE','High',['Quy tắc chia thưởng được chốt; tổng hợp kỳ đối soát được với chứng từ.','Owner isolation áp cả API lẫn file xuất; đổi horseId không đọc dữ liệu khác.','Kỳ chưa dữ liệu/thiếu hợp đồng/lỗi xuất hiển thị rõ; không tự điền tỷ lệ chia.']],
['FR-019','FR-019','Gợi ý huấn luyện có người duyệt','M4','P2 Medium','ai',['MVP-QA','FR-007'],'BE + FE','High',['Dữ liệu đầu vào đủ theo quyết định đã chốt; thiếu thì không sinh kết luận giả.','Gợi ý có lý do, nguồn và đánh giá; không tự áp dụng giáo án/mở khóa y tế.','Owner/role scope, lỗi provider và rủi ro prompt injection được kiểm tra.']],
['FR-020','FR-020','Trợ lý tra cứu theo quyền','M4','P2 Medium','ai',['FR-019','AUTH-SCOPE'],'BE + FE','High',['Câu trả lời dựa nguồn được cấp quyền, có nguồn/ngày và trạng thái không biết.','Không lấy dữ liệu owner khác qua prompt hoặc tài liệu truy hồi.','Không tự kê đơn, thao tác tiền hay Medical Lock; lỗi dịch vụ hiển thị trung thực.']],
];
const authScreens={'AUTH-LOGIN':['AUTH01','SYS01','SYS02'],'AUTH-REGISTER':['AUTH02','AUTH03','AUTH04'],'AUTH-RESET':['AUTH05','AUTH06','AUTH07'],'AUTH-STAFF':['AUTH08','M02','M03'],'AUTH-SCOPE':['SYS01','O01']};
const project='https://github.com/users/MichaelTran1226/projects/2';
const items=tasks.map(([id,fr,title,milestone,priority,area,deps,lead,risk,ac])=>({id,fr,title,milestone,priority,area,deps,lead,risk,ac,repo:id==='UI-V2'?'MichaelTran1226/Racehorse_Training_Management_System_MT_FE':'MichaelTran1226/Racehorse_Training_Management_System_MT_BE',screens:authScreens[id]??screens.filter(s=>(!/^M[34]$/.test(milestone)?s.phase<3:true)&&s.fr.some(f=>fr.split(',').includes(f))).map(s=>s.id),status:'Backlog',owner:'',targetDate:'',issueUrl:''}));
await mkdir(path.join(base,'issues'),{recursive:true});
for(const t of items){
 const body=`# [${t.fr}][${t.id}] ${t.title}\n\nWork ID: ${t.id}\nBlueprint ID: ${t.fr}\nTarget repository: ${t.repo}\nRelated repository: ${t.repo.endsWith('_BE')?'MichaelTran1226/Racehorse_Training_Management_System_MT_FE':'MichaelTran1226/Racehorse_Training_Management_System_MT_BE'}\nProject: ${project}\nStatus: Backlog — draft local, chưa đồng bộ.\nPriority: ${t.priority}\nType: ${t.id==='UI-V2'?'Task':'Story'}\nArea: ${t.area}\nMilestone/Iteration đề xuất: ${t.milestone}\nOwner/Target date: chưa gán; phải có người thật trước Ready.\nLead đề xuất: ${t.lead}\nRisk: ${t.risk}\n\n## Context và phạm vi\n\nTriển khai ${t.title.toLowerCase()} theo SRS/blueprint EquiFlow và UI V2. Nguồn local chưa publish: RACEHORSE-TRAINING-BP, bộ stitch-v2; thay bằng URL file thực sau PR tài liệu. Không dùng yêu cầu Sports Center cũ. Không có phả hệ hoặc video trong scope.\n\nScreens: ${t.screens.join(', ')||'Nền tảng, không màn riêng'}. Xem SCREEN-MAP.md trong gói UI; chỉ dùng màn có evidence review khi bắt đầu FE.\n\n## Acceptance criteria\n\n${t.ac.map(a=>'- [ ] '+a).join('\n')}\n\n## Công việc và ownership\n\n- [ ] Chốt contract, validation, quyền, state lỗi và quyết định còn mở liên quan trong DECISIONS.md.\n- [ ] BE: schema/migration/API/service theo stack đã chốt, tích hợp quyền và audit khi cần.\n- [ ] FE: màn theo screen ID, state/routing/accessibility và tích hợp contract thực.\n- [ ] QA: test dương, âm, quyền và concurrency thích hợp với AC; ghi evidence thật.\n\nPhạm vi file dự kiến: module ${t.area} trong từng repo, test cùng module và tài liệu API. Chưa đặt đường dẫn framework khi chưa chốt stack. Chia thành subtask ≤1 buổi làm nếu ước lượng vượt năng lực một slice; không đánh dấu các checkbox chỉ vì scaffold.\n\n## Dependency / Blocker\n\n${t.deps.length?t.deps.map(d=>'- '+d+' (thay bằng URL issue thật sau sync)').join('\n'):'Không có dependency công việc; cần review và owner.'}\n\nD-01 stack và D-02 onboarding chưa duyệt là blocker của implementation liên quan. Owner/iteration/date hiện chưa được cam kết.\n\n## Verification / Done\n\n- [ ] Lệnh lint/typecheck/build và test hẹp theo stack đã chọn chạy thật, lưu output.\n- [ ] Unit/integration trước, API/E2E sau; UI ở 1280/1440/1920px nếu có.\n- [ ] PR FE và BE liên kết issue chính, review/merge đầy đủ; tài liệu/rollback cập nhật.\n- [ ] Đọc lại Project item, chỉ chuyển Done khi AC đạt. Không suy số issue từ FR.\n\n## Progress comment\n\nProgress: Not started\nSummary: Draft kế hoạch từ UI V2\nEvidence: Chưa có implementation/test evidence\nBranch/PR: Chưa tạo\nNext: Gán owner, chốt dependency và AC\nBlocker: Xem mục Dependency / Blocker\n`;
 await writeFile(path.join(base,`issues/${t.id}.md`),body);
}
const keys=['id','fr','title','repo','milestone','priority','area','status','owner','targetDate','risk','deps','screens','issueUrl'];
const cell=v=>`"${(Array.isArray(v)?v.join(';'):String(v??'')).replaceAll('"','""')}"`;
await writeFile(path.join(base,'backlog.csv'),'\uFEFF'+keys.join(',')+'\r\n'+items.map(t=>keys.map(k=>cell(t[k])).join(',')).join('\r\n'));
await writeFile(path.join(base,'backlog.json'),JSON.stringify(items,null,2));
await writeFile(path.join(base,'todo.md'),'# Backlog triển khai — chưa tạo issue thật\n\nMọi việc đang Backlog. Owner/date sẽ gán trên GitHub sau khi review.\n\n'+items.map(t=>`- [ ] [${t.id} — ${t.title}](issues/${t.id}.md) · ${t.milestone} · ${t.priority} · phụ thuộc: ${t.deps.join(', ')||'không'}`).join('\n')+'\n\n## Checkpoint\n\n- [ ] M0: xác thực năm vai trò, audit, session và không nâng quyền.\n- [ ] M1: hồ sơ, chuồng, owner isolation.\n- [ ] M2: ảnh 2D đúng, Medical Lock concurrency, hành trình MVP.\n- [ ] M3: ca/kho idempotent, giải đua và báo cáo đối soát.\n- [ ] M4: AI dựa dữ liệu và có người duyệt.\n');
const ids=new Set(items.map(t=>t.id));
for(const t of items)for(const dep of t.deps)if(!ids.has(dep))throw Error(`Unknown dependency ${dep}`);
const done=new Set();
function walk(id,stack=new Set()){if(done.has(id))return;if(stack.has(id))throw Error('Dependency cycle '+id);stack.add(id);for(const d of items.find(t=>t.id===id).deps)walk(d,new Set(stack));done.add(id)}
items.forEach(t=>walk(t.id));
console.log(JSON.stringify({issueDrafts:items.length,dependencyGraph:'acyclic',coveredFR:[...new Set(items.flatMap(t=>t.fr.split(',')))].length}));
